- hosts: 'all'
  gather_facts: false
  user: root
  sudo: true

  tasks:
  - sysctl: name=vm.swappiness value=10 state=present
  - sysctl: name=net.ipv4.tcp_mem value="8388608 8388608 8388608" state=present
  - sysctl: name="net.ipv4.tcp_max_tw_buckets" value=6000000 state=present
  - sysctl: name="net.ipv4.tcp_max_syn_backlog" value=65536 state=present
  - sysctl: name="net.ipv4.tcp_max_orphans" value=262144 state=present
  - sysctl: name="net.core.somaxconn" value=16384 state=present
  - sysctl: name="net.core.netdev_max_backlog" value=16384 state=present
  - sysctl: name="net.ipv4.tcp_synack_retries" value=2 state=present
  - sysctl: name="net.ipv4.tcp_syn_retries" value=2 state=present
  - sysctl: name="net.ipv4.tcp_fin_timeout" value=7 state=present
  - sysctl: name="net.ipv4.tcp_slow_start_after_idle" value=0 state=present
  - sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1 state=present
  - sysctl: name="fs.file-max" value=500000 state=present reload=yes
